environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "10"
  EMBARK_NO_PREPARE: true
cache:
 - "%LOCALAPPDATA%\\Yarn"
install:
  - ps: Install-Product node $env:nodejs_version
  - ps: Start-FileDownload 'https://github.com/yarnpkg/yarn/releases/download/v1.12.3/yarn-1.12.3.msi'
  - cmd /c start /wait msiexec.exe /i yarn-1.12.3.msi /quiet /qn /norestart
  - rm yarn-1.12.3.msi
  - node --version
  - npm --version
  - yarn --version
  - yarn install
  - cd embark-ui && yarn install && cd ..
  - npm run check-working-tree
test_script:
  - npm run build:node
  - npm test
  - npm run check-working-tree
build: off
